name: 'LB Design '
favicon: null
layout_spectrum: 0.6273777829483151
typography_spectrum: 0.9403480025939643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9736518356949091
  lightness: 0.7333949087187648
  saturation: 0.3823029575869441
  rhythmicContrast: 0.8572979678865522
purpose: []
